requires=["tox>=4.24.1"]
env_list=["py3.13", "dev"]

[env_run_base]
    description="Run the tests with pytest under {env_name}"
    package="wheel"
    dependency_groups=["base"]
    commands=[["pytest test", { replace="posargs", extend=true }]]

[env_pkg_base]
    description="Package the project into a wheel"
    package="wheel"
    dependency_groups=["base"]
    commands=[["python", "-m", "build", "--wheel"]]

[env.dev]
    description="Development environment"
    package="editable"
    dependency_groups=["dev"]
    commands=[["python", "-m", "pip", "install", "-e", "."]]

[env.build]
    description="Package the project into a wheel"
    package="wheel"
    skip_install=true
    dependency_groups=["base"]
    commands=[["python", "-m", "build", "--wheel"]]
